;Generated by UVtools v4.3.2 64-bits @ 5/10/2024 12:43:47 PM
;fileName:
;machineType:Phrozen Sonic Mega 8K S
;estimatedPrintTime:{estimatedPrintTime:d}
;volume:{volume:d}
;resin:
;weight:{weight:d}
;price:0.294
;layerHeight:0.05
;resolutionX:7680
;resolutionY:4320
;machineX:330.24
;machineY:185.76
;machineZ:300
;projectType:Normal
;normalExposureTime:3
;bottomLayExposureTime:30
;bottomLayerExposureTime:30
;normalDropSpeed:100
;normalLayerLiftSpeed:100
;normalLayerLiftHeight:5
;zSlowUpDistance:0
;bottomLayCount:4
;bottomLayerCount:4
;mirror:0
;totalLayer:{totalLayer:d}
;bottomLayerLiftHeight:5
;bottomLayerLiftSpeed:100
;bottomLightOffTime:0
;lightOffTime:0
;bottomPWMLight:255
;PWMLight:255
;antiAliasLevel:1

;START_GCODE_BEGIN
G21;Set units to be mm
G90;Absolute positioning
M17;Enable motors
M106 S0;Turn LED OFF
;<Slice> Blank
G28 Z0;Home Z
;END_GCODE_BEGIN

